### PR TITLE
Remove dependency on ActiveSupport

### PR DESCRIPTION
**Pull request by oneiros**
Since we agreed to remove ActiveSupport as a dependency I though I would try to get rid of it.

Two instances of AS method usage were easy to remove:

* `html_safe` only makes sense in the context of Rails anyway and can be safely removed. phlex has its own mechanism to sanititze outputs and does not know nor care about `ActiveSupport::SafeBuffer`s.
* `present?` is mostly about syntactic sugar and can also be removed easily.

Sadly, there is a third place where AS methods are being used and where replacing / removing them is not trivial: `PhlexUI::Select::Builder` uses the `String` extensions `classify`, `constantize` and `underscore`. I will open a new issue with ideas how to proceed.

### CODE REVIEW

**Comment by cirdes** [comment]
I agree that we should remove ActiveSupport as a dependency

**Comment by iseth** [comment]
https://github.com/PhlexUI/phlex_ui/issues/44#issuecomment-2099155907

**Review by cirdes — APPROVED** [review]
Looks great!

**Review by cirdes — CHANGES_REQUESTED** [review]
@oneiros could you remove  "s.add_dependency "activesupport", ">= 6.0"" from gemspec too?

**Comment by cirdes** [comment]
@oneiros , I tried to update you branch to remove 'activesupport' but I couldn't. Could you remove it so we could be able to merge?

**Comment by oneiros** [comment]
The dependency should be gone (again).

**Review by cirdes — APPROVED** [review]

**Comment by cirdes** [comment]
@iseth , could you merge this?

**Review by iseth — APPROVED** [review]
Looks great. Thanks!! 💯

**Pull request merged**
